create database customer_shopping
GO
use customer_shopping
select * from customer_data


--Q1. What is the total revenue generated by male vs. female customers?
select gender, sum(purchase_amount) as revenue from customer_data
group by gender;

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount from customer_data
where discount_applied='Yes' and purchase_amount >= (select avg(purchase_amount) from customer_data)

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,round(avg(review_rating),2) as avg_rating from customer_data
group by item_purchased
order by avg(review_rating) desc

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type,avg(purchase_amount) as avg_amount from customer_data
where shipping_type in ('Express','Standard')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,count(*) as total_customer,
sum(purchase_amount) as revenue, 
avg(purchase_amount)as avg_spend from customer_data
group by subscription_status
order by revenue desc, avg_spend desc

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select top 5 item_purchased,
cast(round(100.0*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as decimal(10,2)) as discount_rate
 from customer_data
group by item_purchased
order by discount_rate desc

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

with customer as(
select customer_id, previous_purchases,
case
when previous_purchases= 1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal' end as customer_segment
from customer_data
)
select customer_segment,count(customer_id) as total from customer
group by customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
with cte as(
 select category,item_purchased, count(customer_id) as total_purchase,
 ROW_NUMBER() over(partition by category order by  count(customer_id) desc ) as rn
 from customer_data
 group by category,item_purchased
 )
select category,item_purchased,total_purchase from cte
where rn<=3

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status, count(customer_id) as repeat_buyers from customer_data
where previous_purchases>5
group by subscription_status

--Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount) as total_revenue from customer_data
group by age_group
order by total_revenue desc


